/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvaluationsIdRouteImport } from './routes/evaluations.$id'
import { Route as ParentIntakeTokenRouteImport } from './routes/parent-intake.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsIdRoute = EvaluationsIdRouteImport.update({
  id: '/evaluations/$id',
  path: '/evaluations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIntakeTokenRoute = ParentIntakeTokenRouteImport.update({
  id: '/parent-intake/$token',
  path: '/parent-intake/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evaluations/$id': typeof EvaluationsIdRoute
  '/parent-intake/$token': typeof ParentIntakeTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evaluations/$id': typeof EvaluationsIdRoute
  '/parent-intake/$token': typeof ParentIntakeTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evaluations/$id': typeof EvaluationsIdRoute
  '/parent-intake/$token': typeof ParentIntakeTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/evaluations/$id' | '/parent-intake/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/evaluations/$id' | '/parent-intake/$token'
  id: '__root__' | '/' | '/evaluations/$id' | '/parent-intake/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvaluationsIdRoute: typeof EvaluationsIdRoute
  ParentIntakeTokenRoute: typeof ParentIntakeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations/$id': {
      id: '/evaluations/$id'
      path: '/evaluations/$id'
      fullPath: '/evaluations/$id'
      preLoaderRoute: typeof EvaluationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-intake/$token': {
      id: '/parent-intake/$token'
      path: '/parent-intake/$token'
      fullPath: '/parent-intake/$token'
      preLoaderRoute: typeof ParentIntakeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvaluationsIdRoute: EvaluationsIdRoute,
  ParentIntakeTokenRoute: ParentIntakeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
