/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvaluationsIdRouteImport } from './routes/evaluations.$id'
import { Route as ParentIntakeTokenRouteImport } from './routes/parent-intake.$token'
import { Route as TeacherIntakeTokenRouteImport } from './routes/teacher-intake.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsIdRoute = EvaluationsIdRouteImport.update({
  id: '/evaluations/$id',
  path: '/evaluations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIntakeTokenRoute = ParentIntakeTokenRouteImport.update({
  id: '/parent-intake/$token',
  path: '/parent-intake/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIntakeTokenRoute = TeacherIntakeTokenRouteImport.update({
  id: '/teacher-intake/$token',
  path: '/teacher-intake/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evaluations/$id': typeof EvaluationsIdRoute
  '/parent-intake/$token': typeof ParentIntakeTokenRoute
  '/teacher-intake/$token': typeof TeacherIntakeTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evaluations/$id': typeof EvaluationsIdRoute
  '/parent-intake/$token': typeof ParentIntakeTokenRoute
  '/teacher-intake/$token': typeof TeacherIntakeTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evaluations/$id': typeof EvaluationsIdRoute
  '/parent-intake/$token': typeof ParentIntakeTokenRoute
  '/teacher-intake/$token': typeof TeacherIntakeTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evaluations/$id'
    | '/parent-intake/$token'
    | '/teacher-intake/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evaluations/$id'
    | '/parent-intake/$token'
    | '/teacher-intake/$token'
  id:
    | '__root__'
    | '/'
    | '/evaluations/$id'
    | '/parent-intake/$token'
    | '/teacher-intake/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvaluationsIdRoute: typeof EvaluationsIdRoute
  ParentIntakeTokenRoute: typeof ParentIntakeTokenRoute
  TeacherIntakeTokenRoute: typeof TeacherIntakeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations/$id': {
      id: '/evaluations/$id'
      path: '/evaluations/$id'
      fullPath: '/evaluations/$id'
      preLoaderRoute: typeof EvaluationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-intake/$token': {
      id: '/parent-intake/$token'
      path: '/parent-intake/$token'
      fullPath: '/parent-intake/$token'
      preLoaderRoute: typeof ParentIntakeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-intake/$token': {
      id: '/teacher-intake/$token'
      path: '/teacher-intake/$token'
      fullPath: '/teacher-intake/$token'
      preLoaderRoute: typeof TeacherIntakeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvaluationsIdRoute: EvaluationsIdRoute,
  ParentIntakeTokenRoute: ParentIntakeTokenRoute,
  TeacherIntakeTokenRoute: TeacherIntakeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
